In [4]:
text = """
Artificial intelligence is transforming the world in many different ways.
It is helping doctors diagnose diseases more accurately and assisting teachers in providing personalized education.
Machine learning is a branch of artificial intelligence that enables computers to learn from data without being explicitly programmed.
Deep learning is a specialized field of machine learning that uses artificial neural networks with multiple hidden layers.
Natural language processing allows computers to understand, analyze, and generate human language.
Computer vision enables machines to recognize images, detect objects, and identify faces.
Artificial intelligence is widely used in healthcare, banking, agriculture, transportation, manufacturing, cybersecurity, and entertainment.
Companies use artificial intelligence to improve customer service through chatbots and virtual assistants.
Recommendation systems suggest movies, songs, books, and products based on user preferences.
Self-driving cars rely on artificial intelligence to detect roads, traffic signs, pedestrians, and other vehicles.
Data is one of the most valuable resources in artificial intelligence because machine learning models depend on high-quality datasets.
Data preprocessing includes cleaning missing values, removing duplicates, handling outliers, and scaling numerical features.
Feature engineering helps improve the performance of machine learning algorithms.
Supervised learning uses labeled data, while unsupervised learning discovers hidden patterns in unlabeled data.
Reinforcement learning trains agents to make decisions by maximizing rewards through interaction with an environment.
Python is one of the most popular programming languages for artificial intelligence because it provides powerful libraries.
NumPy is used for numerical computations, Pandas is used for data manipulation, Matplotlib and Seaborn are used for visualization, and TensorFlow and Keras are used for deep learning.
Long Short-Term Memory networks are a type of recurrent neural network designed to remember information over long sequences.
LSTM models are commonly used for text generation, sentiment analysis, speech recognition, language translation, and time series forecasting.
Tokenization converts sentences into numerical sequences that deep learning models can understand.
Word embeddings represent words as dense vectors that capture semantic meaning.
Padding ensures that all input sequences have the same length before they are passed into the neural network.
The embedding layer converts word indices into dense vector representations that are learned during training.
Training a deep learning model involves forward propagation, loss calculation, backpropagation, and optimization.
The Adam optimizer is widely used because it combines the advantages of momentum and adaptive learning rates.
Categorical crossentropy is commonly used as the loss function for multi-class classification problems.
The quality of a language model improves when it is trained on a larger and more diverse dataset.
Generative artificial intelligence can generate text, images, audio, and videos using deep neural networks.
Large language models are trained on billions of words collected from books, articles, websites, and research papers.
Continuous learning and practice are essential for becoming an expert in artificial intelligence and data science.
"""

In [5]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical

In [7]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

total_words = len(tokenizer.word_index) 

print(tokenizer.word_index)
print("Vocabulary Size:", total_words)

{'and': 1, 'learning': 2, 'is': 3, 'the': 4, 'artificial': 5, 'intelligence': 6, 'of': 7, 'used': 8, 'for': 9, 'are': 10, 'to': 11, 'data': 12, 'in': 13, 'a': 14, 'that': 15, 'deep': 16, 'language': 17, 'on': 18, 'it': 19, 'machine': 20, 'neural': 21, 'models': 22, 'networks': 23, 'because': 24, 'numerical': 25, 'sequences': 26, 'into': 27, 'more': 28, 'enables': 29, 'computers': 30, 'from': 31, 'uses': 32, 'with': 33, 'hidden': 34, 'understand': 35, 'generate': 36, 'images': 37, 'detect': 38, 'widely': 39, 'improve': 40, 'through': 41, 'books': 42, 'one': 43, 'most': 44, 'quality': 45, 'an': 46, 'long': 47, 'network': 48, 'commonly': 49, 'text': 50, 'converts': 51, 'can': 52, 'word': 53, 'words': 54, 'as': 55, 'dense': 56, 'training': 57, 'model': 58, 'loss': 59, 'trained': 60, 'transforming': 61, 'world': 62, 'many': 63, 'different': 64, 'ways': 65, 'helping': 66, 'doctors': 67, 'diagnose': 68, 'diseases': 69, 'accurately': 70, 'assisting': 71, 'teachers': 72, 'providing': 73, 'perso

In [8]:
input_sequences = []

for line in text.split('.'):
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequences.append(n_gram)

print(input_sequences)

[[5, 6], [5, 6, 3], [5, 6, 3, 61], [5, 6, 3, 61, 4], [5, 6, 3, 61, 4, 62], [5, 6, 3, 61, 4, 62, 13], [5, 6, 3, 61, 4, 62, 13, 63], [5, 6, 3, 61, 4, 62, 13, 63, 64], [5, 6, 3, 61, 4, 62, 13, 63, 64, 65], [19, 3], [19, 3, 66], [19, 3, 66, 67], [19, 3, 66, 67, 68], [19, 3, 66, 67, 68, 69], [19, 3, 66, 67, 68, 69, 28], [19, 3, 66, 67, 68, 69, 28, 70], [19, 3, 66, 67, 68, 69, 28, 70, 1], [19, 3, 66, 67, 68, 69, 28, 70, 1, 71], [19, 3, 66, 67, 68, 69, 28, 70, 1, 71, 72], [19, 3, 66, 67, 68, 69, 28, 70, 1, 71, 72, 13], [19, 3, 66, 67, 68, 69, 28, 70, 1, 71, 72, 13, 73], [19, 3, 66, 67, 68, 69, 28, 70, 1, 71, 72, 13, 73, 74], [19, 3, 66, 67, 68, 69, 28, 70, 1, 71, 72, 13, 73, 74, 75], [20, 2], [20, 2, 3], [20, 2, 3, 14], [20, 2, 3, 14, 76], [20, 2, 3, 14, 76, 7], [20, 2, 3, 14, 76, 7, 5], [20, 2, 3, 14, 76, 7, 5, 6], [20, 2, 3, 14, 76, 7, 5, 6, 15], [20, 2, 3, 14, 76, 7, 5, 6, 15, 29], [20, 2, 3, 14, 76, 7, 5, 6, 15, 29, 30], [20, 2, 3, 14, 76, 7, 5, 6, 15, 29, 30, 11], [20, 2, 3, 14, 76, 7, 5

In [9]:
max_len = max(len(seq) for seq in input_sequences)

input_sequences = pad_sequences(
    input_sequences,
    maxlen=max_len,
    padding='pre'
)

print(input_sequences)

[[  0   0   0 ...   0   5   6]
 [  0   0   0 ...   5   6   3]
 [  0   0   0 ...   6   3  61]
 ...
 [  0   0   0 ...   5   6   1]
 [  0   0   0 ...   6   1  12]
 [  0   0   0 ...   1  12 270]]
